blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [
    path('', views.BlogPostListView.as_view(), name='blog_post_list'),
    path('blog/create/', views.BlogPostCreateView.as_view(), name='blog_post_create'),
    path('blog/update/<slug:slug>/', views.BlogPostUpdateView.as_view(), name='blog_post_update'),
    path('blog/delete/<slug:slug>/', views.BlogPostDeleteView.as_view(), name='blog_post_delete'),
    path('blog/<slug:slug>/', cache_page(60)(views.BlogPostDetailView.as_view()), name='blog_post_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mailing.urls')),
    path('', include('clients.urls')),
    path('', include('logs.urls')),
    path('', include('users.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('mailings/', views.MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', views.MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', views.MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', views.MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', views.MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/add_clients/<int:pk>/', views.AddClientsToMailingView.as_view(), name='add_clients_to_mailing'),
    path('message/create/', views.MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', views.MessageUpdateView.as_view(), name='message_update'),
    path('complete_mailing/<int:pk>/', views.complete_mailing, name='complete_mailing'),
]

mailing/models.py
from django.db import models
from clients.models import Client
from config import settings

NULLABLE = {'null': True, 'blank': True}

class Mailing(models.Model):
    SEND_CHOICES = (
        ('daily', 'раз в день'),
        ('weekly', 'раз в неделю'),
        ('monthly', 'раз в месяц'),
    )
    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    )
    start_date = models.DateTimeField(verbose_name="Дата начала рассылки", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="Дата окончания рассылки", null=True, blank=True)
    send_time = models.TimeField(verbose_name="Время рассылки")
    send_frequency = models.CharField(max_length=10, choices=SEND_CHOICES, verbose_name="Частота рассылки")
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='created', verbose_name="Статус рассылки")
    clients = models.ManyToManyField(Client, verbose_name="Клиенты", related_name="mailings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE, verbose_name="Пользователь")
    def __str__(self):
        return f"{self.send_time} {self.send_frequency}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='Тема')
    body = models.TextField(verbose_name='Сообщение')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, **NULLABLE, verbose_name='Рассылка')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

mailing/forms.py
from django import forms
from django.forms import SelectDateWidget
from .models import Mailing, Message


class MailingForm(forms.ModelForm):
    start_date = forms.DateTimeField(
        widget=SelectDateWidget(attrs={'class': 'date-input'}),
    )
    end_date = forms.DateTimeField(
        widget=SelectDateWidget(attrs={'class': 'date-input'}),
    )

    class Meta:
        model = Mailing
        exclude = ['clients']

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message

        fields = ['subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

mailing/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import MailingForm, MessageForm
from .models import Mailing, Message
from clients.models import Client
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'mailings'

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset().select_related('user')
        if user.groups.filter(name='Менеджер').exists():
            return queryset
        else:
            return queryset.filter(user=user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'mailing'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.get_object()
        context['message'] = Message.objects.get(mailing=mailing)
        return context


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'mailing.add_mailing'
    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm
    success_url = reverse_lazy('message_create')

    def form_valid(self, form):
        mailing = form.save(commit=False)
        mailing.status = 'created'
        mailing.user = self.request.user
        mailing.save()
        self.request.session['mailing_id'] = mailing.id
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'mailing.change_mailing'
    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm

    def form_valid(self, form):
        mailing = form.save(commit=False)
        if not mailing.user:
            mailing.user = self.request.user
        mailing.save()
        return super().form_valid(form)

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_success_url(self):
        return reverse_lazy('mailing_detail', kwargs={'pk': self.object.id})


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'mailing.delete_mailing'
    model = Mailing
    template_name = 'mailing/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailing_list')

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class MessageCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'mailing.add_message'
    model = Message
    template_name = 'mailing/message_form.html'
    form_class = MessageForm

    def form_valid(self, form):
        mailing_id = self.request.session.get('mailing_id')
        if mailing_id:
            mailing = Mailing.objects.get(id=mailing_id)
            form.instance.mailing = mailing
        mailing.save()
        mailing_id = mailing.id
        self.request.session['current_stage'] = 'add_clients'
        self.success_url = reverse_lazy('add_clients_to_mailing', kwargs={'pk': mailing_id})

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'mailing.change_message'
    model = Message
    template_name = 'mailing/message_form.html'
    form_class = MessageForm

    def get_queryset(self):
        return super().get_queryset().filter(mailing__user=self.request.user)

    def form_valid(self, form):
        mailing = self.object.mailing

        self.success_url = reverse_lazy('mailing_detail', kwargs={'pk': mailing.id})

        return super().form_valid(form)


class AddClientsToMailingView(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'mailing.change_mailing'
    template_name = 'mailing/add_clients_to_mailing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_id = self.kwargs['pk']

        mailing = get_object_or_404(Mailing, pk=mailing_id, user=self.request.user)

        search_query = self.request.GET.get('search', '')

        context['mailing_id'] = mailing_id
        context['selected_clients'] = mailing.clients.all()

        query = Q(full_name__icontains=search_query) | Q(email__icontains=search_query)

        context['clients'] = Client.objects.filter(query, user=self.request.user)

        return context

    def post(self, request, *args, **kwargs):
        mailing_id = self.kwargs.get('pk')

        mailing = get_object_or_404(Mailing, pk=mailing_id, user=self.request.user)

        selected_clients = request.POST.getlist('clients')

        mailing.clients.clear()
        mailing.clients.add(*Client.objects.filter(id__in=selected_clients, user=self.request.user))

        return redirect('mailing_list')


@login_required
def complete_mailing(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)

    if request.user.groups.filter(name='Менеджер').exists():
        mailing.status = 'completed'
        mailing.save()
        messages.success(request, 'Рассылка завершена.')
    else:
        messages.error(request, 'У вас нет прав на выполнение этой операции.')

    return redirect(reverse_lazy('mailing_detail', args=[pk]))

mailing/templates/mailing/add_clients_to_mailing.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="h2">Выберите клиентов для рассылки</h1>
        <a href="{% url 'client_form' %}?next={{ request.path }}" class="btn btn-light" data-toggle="tooltip" data-placement="top" title="Добавить нового клиента">
            <img src="{% static 'images/add_icon.png' %}" alt="Добавить клиента" style="width: 30px; height: 30px;">
        </a>
    </div>

    <form class="form-inline mb-3">
        <div class="input-group">
            <input type="text" name="search" class="form-control" placeholder="Поиск по клиентам..." aria-label="Поиск по клиентам">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Поиск</button>
            </div>
        </div>
    </form>

    <form method="post" action="{% url 'add_clients_to_mailing' mailing_id %}">
        {% csrf_token %}
        <div class="table-responsive">
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Email</th>
                        <th scope="col">Клиент</th>
                        <th scope="col">Выбрать</th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in clients %}
                        <tr>
                            <th scope="row">{{ client.id }}</th>
                            <td>{{ client.email }}</td>
                            <td>{{ client.full_name }}</td>
                            <td>
                                <input class="form-check-input" type="checkbox" name="clients" value="{{ client.id }}"
                                       {% if client in selected_clients %} checked {% endif %}>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Сохранить выбор</button>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/base.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>...i v production</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Mailing App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blog_post_list' %}">Главная <span class="sr-only">(current)</span></a>
                    </li>
                    {% if user|is_manager %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users_list' %}">Пользователи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mailing_list' %}">Рассылки</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mailing_list' %}">Мои рассылки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clients_list' %}">Мои клиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'log_list' %}">Логи рассылок</a>
                        </li>
                    {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' user.pk %}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-3">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/jquery-3.7.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Подтверждение удаления рассылки</h1>
    <p>Вы уверены, что хотите удалить рассылку "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'mailing_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="card shadow">
        <div class="card-body">
            <h1 class="card-title">Детали рассылки</h1>
            <p class="card-text"><strong>ID:</strong> {{ mailing.id }}</p>
            <p class="card-text"><strong>Время рассылки:</strong> {{ mailing.send_time }}</p>
            <p class="card-text"><strong>Периодичность:</strong> {{ mailing.send_frequency }}</p>
            <p class="card-text"><strong>Статус:</strong> {{ mailing.status }}</p>
            <p class="card-text"><strong>Дата начала:</strong> {{ mailing.start_date }}</p>
            <p class="card-text"><strong>Дата окончания:</strong> {{ mailing.end_date }}</p>
            <p class="card-text"><strong>Клиенты:</strong>
                {% for client in mailing.clients.all %}
                    {{ client.full_name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>
    </div>

    <div class="btn-group mt-3" role="group">
        {% if user|is_manager %}
            {% if mailing.status != 'completed' %}
                <a href="{% url 'complete_mailing' mailing.pk %}" class="btn btn-success">
                    <i class="fas fa-check"></i> Завершить рассылку
                </a>
            {% endif %}
        {% else %}
            <a href="{% url 'mailing_update' mailing.pk %}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Обновить настройки рассылки">
                <img src="{% static 'images/edit_settings_icon.png' %}" alt="update_mailing" style="width: 30px; height: 30px;">
            </a>
            <a href="{% url 'message_update' message.pk %}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Редактировать сообщение">
                <img src="{% static 'images/edit_mail_icon.png' %}" alt="edit_mail" style="width: 30px; height: 30px;">
            </a>
            <a href="{% url 'add_clients_to_mailing' mailing.pk %}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Добавить клиентов">
                <img src="{% static 'images/add_clients_icon.png' %}" alt="add_clients" style="width: 30px; height: 30px;">
            </a>
            <a href="{% url 'mailing_delete' mailing.pk %}" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Удалить рассылку">
                <img src="{% static 'images/delete_icon.png' %}" alt="delete_mailing" style="width: 30px; height: 30px;">
            </a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_js %}
  <script src="https://kit.fontawesome.com/your-fontawesome-kit.js"></script> <!-- Подключение FontAwesome -->
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-4">
        <div class="col text-center">
            <h1>{% if object %}Обновить рассылку{% else %}Создать рассылку{% endif %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" class="card">
                {% csrf_token %}
                <div class="card-body">
                    <div class="form-row">
                        <!-- Левая колонка для дат -->
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                {{ form.start_date.label_tag }}
                                {{ form.start_date }}
                            </div>
                            <div class="form-group">
                                {{ form.end_date.label_tag }}
                                {{ form.end_date }}
                            </div>
                        </div>
                        <!-- Правая колонка для времени, частоты и статуса -->
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                {{ form.send_frequency.label_tag }}
                                {{ form.send_frequency }}
                            </div>
                            <div class="form-group">
                                {{ form.send_time.label_tag }}
                                {{ form.send_time }}
                            </div>
                            <div class="form-group">
                                {{ form.status.label_tag }}
                                {{ form.status }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-primary">Далее</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="mr-3">Список рассылок</h1>
        {% if not user|is_manager %}
            <a href="{% url 'mailing_create' %}" class="btn btn-light" data-toggle="tooltip" data-placement="top" title="Добавить рассылку">
                <img src="{% static 'images/add_icon.png' %}" alt="Добавить рассылку" style="width: 30px; height: 30px;">
            </a>
        {% endif %}
    </div>
    <table class="table table-secondary table-hover">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                {% if user|is_manager %}
                    <th>Email пользователя</th>
                {% endif %}
                <th>Время рассылки</th>
                <th>Периодичность</th>
                <th>Статус</th>
                <th>Детали</th>
            </tr>
        </thead>
        <tbody>
            {% for mailing in mailings %}
            <tr>
                <td>{{ mailing.id }}</td>
                {% if user|is_manager %}
                    <td>{{ mailing.user.email }}</td>
                {% endif %}
                <td>{{ mailing.send_time }}</td>
                <td>{{ mailing.send_frequency }}</td>
                <td>{{ mailing.status }}</td>
                <td>
                    <a href="{% url 'mailing_detail' mailing.pk %}" class="btn btn-outline-secondary"data-toggle="tooltip" data-placement="top" title="Подробнее">
                        <img src="{% static 'images/more_detail.png' %}" alt="подробнее" style="width: 30px; height: 30px;">
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">Нет доступных рассылок.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col">
        <h1>Подтвердите удаление сообщения</h1>
        <p>Вы уверены, что хотите удалить это сообщение?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'message_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-4">
        <div class="col text-center">
            <h1>{% if object %}Обновить сообщение{% else %}Добавить сообщение{% endif %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" class="card">
                {% csrf_token %}
                <div class="card-body">
                    {{ form.as_p }}
                </div>
            <div class="card-footer text-right">
                <button type="submit" class="btn btn-primary">Далее</button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}